spring:
  ai:
    mcp:
      client:
        sse:
          connections: 
            product: http://localhost:8071
    ollama:
      base-url: http://localhost:11434  
      chat:
        options:
          model: qwen3:0.6b
      embedding:
        options:
          model: all-minilm
  vectorstore:
    qdrant:
      initialize-schema: true
      host: localhost
      port: 6333
      collection-name: vector_store 
      use-tls: false
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.vectorstore: DEBUG
    org.springframework.ai.retrieval: DEBUG
server:
  port: 7779