spring:
  datasource:
    url: jdbc:mysql://localhost:3308/payment
    username: root
    password: LuisPiquinRey
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    preferIpAddress: true
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

axon:
  axonserver:
    servers: localhost:8124

axoniq:
  console:
    application-name: Shopping-axion
    credentials: ${CREDENTIALS_AXION}
    dlq-mode: FULL
server:
  port: 9050