server:
    port: 8080
spring: 
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    import:
      - "product_test.yml"
      - "product_dev.yml"
eureka:
  instance:
    preferIpAddress: true
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS
axon:
  axonserver:
    servers: localhost:8124
axoniq:
  console:
    application-name: Shopping-axion
    credentials: ${CREDENTIALS_AXION}
    dlq-mode: FULL
