spring:
  config:
    activate:
      on-profile: "test"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: LuisPiquinRey
    password: '{cipher}fef3e59cdad42e36000fd0d95649ae0c78000b11ac625ab0ceb98466f0497e47'
  jpa:
    hibernate:
      ddl-auto: create-drop