spring:
    application:
        name: discovery
    config:
        import: configserver:http://localhost:8090/
    cloud:
        config:
            uri: http://localhost:8090
            fail-fast: true
